apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler

metadata:
        name: hpa-dl
        namespace: ns-vujade

spec:
        scaleTargetRef:
                apiVersion: apps/v1
                kind: Deployment
                name: dep-dl
        minReplicas: 3
        maxReplicas: 12
        metrics:
        - type: Resource
          resource:
                  name: cpu
                  target:
                          type: Utilization
                          averageUtilization: 65
