apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
 
metadata:
  name: vujade-cluster
  region: ap-northeast-2
  version: "1.21"
 
vpc:
  subnets:
    private:
      ap-northeast-2a: { id: subnet-012a3456b78cde9f0 }
      ap-northeast-2c: { id: subnet-0123a4bc5d678e901 }
secretsEncryption:
  keyARN: arn:aws:kms:ap-northeast-2:123456789123:key/a0b1234c-de5f-6789-g01h-2i3456j789k0
