apiVersion: v1
kind: Service
metadata:
        name: svc-dl
        namespace: ns-vujade
spec:
        selector:
                app: eks-dl
        type: NodePort
        ports:
                - protocol: TCP
                  port: 11001
                  targetPort: 11001
